stages:
  - build
  - deploy

latexmk:
  stage: build
  image: dettmering/latex-build
  script:
    - latexmk -pdf thesis.tex
  artifacts:
    paths:
      - ./*.pdf
    expire_in: 1 day

pages:
  stage: deploy
  script:
    - mkdir .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
  - master
